<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateProgramFile>true</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="InventoryTests.fs" />
    <Compile Include="StoreTests.fs" />
    <Compile Include="CliTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Administration.Installations/Administration.Installations.fsproj" />
    <ProjectReference Include="../../src/Administration.Cli/Administration.Cli.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

</Project>
